/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/potted-plant.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/potted-plant.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Potted_Plant000.geometry} material={materials.Material} scale={100} />
    </group>
  )
}

useGLTF.preload('/potted-plant.glb')
